/** Plain-language finance terms, Arabic and English. `match` lists the forms a term appears in, in either
 *  language, so the reports' text can be linked to an explanation. Keep each explanation one or two sentences. */
export type Term = { id: string; ar: string; en: string; match: string[]; def_ar: string; def_en: string };

export const TERMS: Term[] = [
  { id: "rsi", ar: "مؤشر القوة النسبية (RSI)", en: "RSI (Relative Strength Index)", match: ["RSI", "القوة النسبية"],
    def_ar: "رقم من 0 إلى 100 يقيس سرعة الصعود والنزول الأخيرة. فوق 70 يعني السهم ارتفع بسرعة (تشبّع شراء)، وتحت 30 نزل بسرعة (تشبّع بيع).",
    def_en: "A 0–100 gauge of how fast the price moved lately. Above 70 = rose very fast (overbought); below 30 = fell very fast (oversold)." },
  { id: "macd", ar: "مؤشر الماكد (MACD)", en: "MACD", match: ["MACD", "الماكد"],
    def_ar: "يقارن متوسطين للسعر (قصير وطويل) ليوضح هل الزخم يتسارع للأعلى أو للأسفل.",
    def_en: "Compares a short and a long average of the price to show whether momentum is speeding up or slowing down." },
  { id: "ma", ar: "المتوسط المتحرك", en: "Moving average", match: ["moving average", "SMA", "EMA", "50-day", "200-day", "المتوسط المتحرك", "متوسط 50", "متوسط 200"],
    def_ar: "متوسط سعر السهم لآخر عدد من الأيام (مثل 50 أو 200 يوم). السعر فوقه غالباً يعني اتجاه صاعد.",
    def_en: "The average price over the last N days (e.g. 50 or 200). A price above it usually means an uptrend." },
  { id: "support", ar: "الدعم والمقاومة", en: "Support and resistance", match: ["support level", "resistance level", "مستوى الدعم", "مستوى المقاومة", "الدعم والمقاومة"],
    def_ar: "الدعم مستوى سعر يميل السهم يرتد عنده للأعلى، والمقاومة مستوى يصعب يتجاوزه.",
    def_en: "Support is a price where the stock tends to bounce up; resistance is a price it struggles to break above." },
  { id: "volatility", ar: "التذبذب", en: "Volatility", match: ["volatility", "volatile", "ATR", "التذبذب", "تقلب"],
    def_ar: "مقدار ما يتحرك السعر صعوداً ونزولاً. تذبذب عالي = مخاطرة وفرص أكبر.",
    def_en: "How much the price swings up and down. Higher volatility = more risk and more opportunity." },
  { id: "volume", ar: "حجم التداول", en: "Volume", match: ["trading volume", "حجم التداول"],
    def_ar: "عدد الأسهم اللي انباعت وانشرت في الفترة. حجم كبير مع الحركة يعني اهتمام قوي.",
    def_en: "How many shares changed hands. Big volume with a move means strong interest." },
  { id: "pe", ar: "مكرر الربحية (P/E)", en: "P/E ratio", match: ["P/E", "PE ratio", "price-to-earnings", "مكرر الربحية", "مكرر الأرباح"],
    def_ar: "سعر السهم مقسوم على ربح السهم السنوي. يوضح كم تدفع مقابل كل ريال ربح؛ رقم عالي يعني السوق متوقع نمو أو السهم غالي.",
    def_en: "Share price divided by yearly earnings per share: what you pay for each unit of profit. High = growth expected, or expensive." },
  { id: "eps", ar: "ربحية السهم (EPS)", en: "EPS (earnings per share)", match: ["EPS", "earnings per share", "ربحية السهم"],
    def_ar: "صافي ربح الشركة مقسوم على عدد أسهمها.", def_en: "The company's net profit divided by its number of shares." },
  { id: "revenue", ar: "الإيرادات", en: "Revenue", match: ["revenue", "الإيرادات"],
    def_ar: "كل الفلوس اللي دخلت الشركة من بيع منتجاتها وخدماتها قبل خصم المصاريف.",
    def_en: "All the money a company takes in from sales, before costs." },
  { id: "margin", ar: "هامش الربح", en: "Profit margin", match: ["profit margin", "gross margin", "operating margin", "net margin", "هامش الربح"],
    def_ar: "نسبة الربح من الإيرادات. هامش 20٪ يعني من كل 100 ريال مبيعات يبقى 20 ربح.",
    def_en: "Profit as a share of revenue. A 20% margin keeps 20 of every 100 in sales as profit." },
  { id: "fcf", ar: "التدفق النقدي الحر", en: "Free cash flow", match: ["free cash flow", "FCF", "cash flow", "التدفق النقدي"],
    def_ar: "الكاش اللي يبقى مع الشركة بعد مصاريف التشغيل والاستثمار. يوضح قدرتها على التوزيعات وسداد الديون.",
    def_en: "Cash left after running and investing in the business; it pays dividends and debt." },
  { id: "debt", ar: "نسبة الدين", en: "Debt ratio", match: ["debt-to-equity", "leverage", "المديونية", "الرافعة المالية"],
    def_ar: "كم تعتمد الشركة على القروض مقارنة بأموالها. دين عالي = مخاطرة أعلى إذا ضعفت الأرباح.",
    def_en: "How much the company relies on borrowing versus its own money. More debt = more risk if profits fall." },
  { id: "dividend", ar: "التوزيعات", en: "Dividend", match: ["dividend", "dividends", "dividend yield", "توزيعات الأرباح", "عائد التوزيع"],
    def_ar: "جزء من أرباح الشركة يوزّع نقداً على المساهمين، عادة كل ربع أو نصف سنة.",
    def_en: "A share of profits paid to shareholders in cash, usually quarterly or twice a year." },
  { id: "marketcap", ar: "القيمة السوقية", en: "Market cap", match: ["market cap", "market capitalization", "القيمة السوقية"],
    def_ar: "سعر السهم ضرب عدد الأسهم: قيمة الشركة كاملة في السوق.", def_en: "Share price × number of shares: what the market values the whole company at." },
  { id: "valuation", ar: "التقييم", en: "Valuation", match: ["valuation", "overvalued", "undervalued", "التقييم", "مبالغ في تقييمه", "مقيم بأقل"],
    def_ar: "هل سعر السهم غالي أو رخيص مقارنة بأرباح الشركة ونموها ومنافسيها.",
    def_en: "Whether the price looks expensive or cheap relative to the company's profits, growth and peers." },
  { id: "guidance", ar: "التوجيهات المستقبلية", en: "Guidance", match: ["guidance", "التوجيهات المستقبلية"],
    def_ar: "توقعات الشركة نفسها لأرباحها أو مبيعاتها القادمة.", def_en: "The company's own forecast for its coming sales or profits." },
  { id: "bull", ar: "صاعد / متفائل", en: "Bullish", match: ["bullish", "bull case", "upside", "متفائل", "الصعود"],
    def_ar: "توقع إن السعر بيرتفع. «حجة الصعود» هي أسباب التفاؤل.", def_en: "Expecting the price to rise. The “bull case” is the reasons for optimism." },
  { id: "bear", ar: "هابط / متشائم", en: "Bearish", match: ["bearish", "bear case", "downside", "متشائم", "الهبوط"],
    def_ar: "توقع إن السعر بينزل. «حجة الهبوط» هي المخاطر والأسباب الحذرة.", def_en: "Expecting the price to fall. The “bear case” is the risks and reasons for caution." },
  { id: "overweight", ar: "زيادة تدريجية", en: "Overweight", match: ["Overweight", "زيادة تدريجية"],
    def_ar: "رأي إيجابي بس أهدأ من «شراء»: زِد حصتك من السهم تدريجياً.", def_en: "Positive but milder than Buy: gradually hold more of the stock." },
  { id: "underweight", ar: "تخفيف", en: "Underweight", match: ["Underweight", "تخفيف"],
    def_ar: "رأي سلبي أهدأ من «بيع»: قلّل حصتك تدريجياً.", def_en: "Negative but milder than Sell: gradually hold less of it." },
  { id: "hold", ar: "احتفاظ", en: "Hold", match: ["احتفاظ"],
    def_ar: "لا تشتري زيادة ولا تبيع؛ خلّ اللي عندك.", def_en: "Don't add and don't sell; keep what you have." },
  { id: "stoploss", ar: "وقف الخسارة", en: "Stop-loss", match: ["stop-loss", "stop loss", "وقف الخسارة"],
    def_ar: "سعر تحدده مسبقاً تبيع عنده لو نزل السهم، عشان ما تكبر الخسارة.", def_en: "A price you set in advance to sell at if the stock falls, so a loss can't grow." },
  { id: "target", ar: "السعر المستهدف", en: "Price target", match: ["price target", "target price", "السعر المستهدف"],
    def_ar: "السعر اللي يتوقع المحلل يوصله السهم خلال فترة معينة. تقدير وليس وعد.", def_en: "The price an analyst expects within a period. An estimate, not a promise." },
  { id: "entry", ar: "سعر الدخول", en: "Entry price", match: ["entry price", "سعر الدخول"],
    def_ar: "السعر المقترح للشراء.", def_en: "The suggested price to buy at." },
  { id: "position", ar: "حجم المركز", en: "Position size", match: ["position size", "position sizing", "sizing", "حجم المركز", "حجم الصفقة"],
    def_ar: "كم من محفظتك تحط في هالسهم. مركز صغير يقلل الضرر لو غلط التوقع.", def_en: "How much of your portfolio goes into this stock. Small positions limit the damage if wrong." },
  { id: "diversification", ar: "التنويع", en: "Diversification", match: ["diversification", "diversify", "التنويع"],
    def_ar: "توزيع فلوسك على أسهم وقطاعات مختلفة عشان ما تتضرر كثير من سقوط واحد.", def_en: "Spreading money across stocks and sectors so one fall can't hurt too much." },
  { id: "benchmark", ar: "المؤشر المرجعي", en: "Benchmark", match: ["benchmark", "S&P 500", "TASI", "تاسي", "المؤشر المرجعي"],
    def_ar: "مؤشر يمثل السوق كله (تاسي للسعودي، S&P 500 للأمريكي). نقارن به عشان نعرف هل السهم أفضل من السوق.",
    def_en: "An index for the whole market (TASI in Saudi, S&P 500 in the US). We compare with it to see if a stock beat the market." },
  { id: "alpha", ar: "ألفا (التفوّق)", en: "Alpha", match: ["alpha", "ألفا"],
    def_ar: "الفرق بين عائد السهم وعائد المؤشر بنفس الفترة. موجب = تفوّق على السوق.", def_en: "The stock's return minus the index's over the same time. Positive = beat the market." },
  { id: "sentiment", ar: "المزاج العام", en: "Sentiment", match: ["sentiment", "المزاج العام", "المعنويات"],
    def_ar: "شعور الناس والمستثمرين تجاه السهم (متفائلين أو خايفين)، من الأخبار ومواقع التواصل.", def_en: "How people and investors feel about the stock, from news and social media." },
  { id: "earnings", ar: "نتائج الأرباح", en: "Earnings report", match: ["earnings report", "quarterly results", "نتائج الأرباح", "النتائج الربعية"],
    def_ar: "إعلان الشركة عن أرباحها ومبيعاتها كل ربع سنة، وغالباً يحرّك السعر بقوة.", def_en: "The company's quarterly report of profits and sales; it often moves the price sharply." },
  { id: "liquidity", ar: "السيولة", en: "Liquidity", match: ["liquidity", "السيولة"],
    def_ar: "سهولة بيع وشراء السهم بسرعة بدون ما يتغير سعره كثير.", def_en: "How easily you can buy or sell quickly without moving the price much." },
  { id: "momentum", ar: "الزخم", en: "Momentum", match: ["momentum", "الزخم"],
    def_ar: "قوة اتجاه السعر الحالي؛ السهم اللي زخمه قوي يميل يكمل في نفس الاتجاه لفترة.", def_en: "The strength of the current price trend; strong momentum tends to continue for a while." },
  { id: "interest", ar: "أسعار الفائدة", en: "Interest rates", match: ["interest rate", "interest rates", "Federal Reserve", "أسعار الفائدة"],
    def_ar: "تكلفة الاقتراض. ارتفاعها عادة يضغط على أسعار الأسهم، خصوصاً أسهم النمو.", def_en: "The cost of borrowing. Rising rates usually weigh on stocks, especially growth stocks." },
  { id: "inflation", ar: "التضخم", en: "Inflation", match: ["inflation", "CPI", "التضخم"],
    def_ar: "ارتفاع الأسعار العام مع الوقت، يعني الفلوس تشتري أقل.", def_en: "Prices rising over time, so money buys less." },
  { id: "futures", ar: "العقود الآجلة", en: "Futures", match: ["futures", "العقود الآجلة"],
    def_ar: "اتفاق على شراء أو بيع سلعة (مثل الذهب) بسعر محدد في تاريخ لاحق. أسعار المعادن في التطبيق منها.", def_en: "An agreement to buy or sell a commodity (like gold) later at a set price. The app's metal prices come from these." },
  { id: "etf", ar: "صندوق المؤشرات (ETF)", en: "ETF", match: ["ETF", "صندوق المؤشرات", "الصناديق المتداولة"],
    def_ar: "صندوق يتداول مثل السهم ويحتوي سلة أسهم، فتشتري تنويع بصفقة وحدة.", def_en: "A fund traded like a stock that holds a basket of shares: diversification in one trade." },
  { id: "conviction", ar: "قوة القناعة", en: "Conviction", match: ["conviction", "قوة القناعة"],
    def_ar: "مدى ثقة القرار نفسه كما يوضحه نصه (منخفضة، متوسطة، عالية)، وليست نسبة إحصائية.", def_en: "How confident the decision text itself is (low/medium/high), not a statistic." },
];

export function termById(id: string) { return TERMS.find((t) => t.id === id); }

const esc = (s: string) => s.replace(/[.*+?^${}()|[\]\\/]/g, "\\$&");
/** One regex over every form, longest first so "free cash flow" wins over "cash flow". */
const forms = TERMS.flatMap((t) => t.match.map((m) => ({ m, id: t.id }))).sort((a, b) => b.m.length - a.m.length);
const byForm = new Map(forms.map((f) => [f.m.toLowerCase(), f.id]));
// Latin forms need word boundaries; Arabic forms may carry prefixes like «ال» or «و», so they match as substrings.
export const TERM_RE = new RegExp(forms.map((f) => /[A-Za-z]/.test(f.m) ? `\\b${esc(f.m)}\\b` : esc(f.m)).join("|"), "gi");
export function idForMatch(s: string) { return byForm.get(s.toLowerCase()); }
